name: CI
on:
  push:
    branches:
    - master
env:
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: shelman/flux-events-pubsub
  REGISTRY_HOSTNAME: quay.io
  REGISTRY_USERNAME: shelman+githubbot
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Build docker image
      run: |
        docker build -t "$REGISTRY_HOSTNAME"/"$IMAGE":"$GITHUB_SHA" .

    - name: Publish docker image
      run: |
        docker login -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD" "$REGISTRY_HOSTNAME"
        docker push $REGISTRY_HOSTNAME/$IMAGE:$GITHUB_SHA
        docker tag $REGISTRY_HOSTNAME/$IMAGE:$GITHUB_SHA $REGISTRY_HOSTNAME/$IMAGE:latest
        docker push $REGISTRY_HOSTNAME/$IMAGE:latest
